[package]
name = "shift-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "shift"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
shift-algorithm = { path = "../crates/shift-algorithm" }
shift-statistics = { path = "../crates/shift-statistics" }
